Algoritmo "ativ_5"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 5
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var P1, P2, media:real

Inicio
     escreva("Digite a primeira nota: ")
     leia (P1)

     escreva("Digite a segunda nota: ")
     leia (P2)

     media <- (P1 + P2) / 2
     
     Escreva ("A média entre ", P1, " e ", P2, " é de: ", media)
Fimalgoritmo