Algoritmo "ativ_4"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 4
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var N1:inteiro N2:inteiro result:inteiro

Inicio
      escreva("Digite um número: ")
      leia(N1)
      
      escreva("Digite outro número: ")
      leia(N2)
      
      result <- (N1 + N2)
      
      escreval("A soma de: ", N1, " + ", N2, " é igual a: ", result)
Fimalgoritmo