Algoritmo "ativ_9"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 9
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var quantia:real dolar:real

Inicio
      escreval ("Quantos reais você tem na carteira?")
      leia(quantia)
      
      dolar <- quantia / 3.45
      
      escreval ("Com", quantia, " reais", " você pode comprar", dolar, " doláres.")
Fimalgoritmo