Algoritmo "ativ_12"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 12
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var valor:real
desconto:real
final:real

Inicio
      escreval ("Digite o valor do produto:")
      leia(valor)
      
      desconto <- valor * 0.05
      
      final <- desconto - valor
      
      escreval ("Seu produto, com um desconto de 5% é de:", final)
      
Fimalgoritmo