Algoritmo "ativ_13"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 13
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var sal:real aumento:real final:real

Inicio
      escreval ("Digite o salário do funcionário")
      leia(sal)
      
      aumento <- sal * 0.15
      final <- sal + aumento
      
      escreval ("O funcionário, recebendo um aumento de 15%, tem um salário de:", final)
Fimalgoritmo