Algoritmo "ativ_6"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 6
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var numero:inteiro anterior:inteiro posterior:inteiro

Inicio
     escreva("Qual seu número? ")
     leia (numero)

     anterior <- numero - 1
     
     posterior <- numero + 1
     
     Escreval ("O antecessor de,", numero, " é", anterior, " agora seu posterior é", posterior, ".")
Fimalgoritmo