Algoritmo "ativ_7"
// Disciplina   : Portugol
// Professor   : Monique
// Descrição   : Atividade 7
// Autor(a)    : José Augusto Junior
// Data atual  : 17/04/2025
Var numero:real dobro:real terca: real

Inicio
      escreva ("Digite seu número: ")
      leia(numero)
      
      dobro <- numero * 2

      terca <- numero / 3
      
      escreval ("O dobro de:", numero, " é igual a", dobro, " agora seu terço é", terca, ".")
Fimalgoritmo